
service: pedirPizzas

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  timeout: 30
  memorySize: 512
  lambdaHashingVersion: 20201221
  apiName: apiGateway-${self:provider.stage}-${self:provider.region}
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    ENVIROMENT: ${self:provider.stage}
    PENDING_ORDER_QUEUE:
      Ref: PendingOrdersQueue
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  hacerPedido:
    handler: handler.hacerPedido
    events:
      - http: POST /hacerPedido
        integration: lambda
        response: 
          headers:
            Content-Type: "'application/json'"

resources:
  Resources:
    PendingOrdersQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: PendingOrderQueue-${self:provider.stage}
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-usersTable-${self:provider.region}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1